/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_interact_nati_CallNativeFunction */

//#define JNICALL
//#define JNIEXPORT

#ifndef _Included_com_interact_nati_CallNativeFunction
#define _Included_com_interact_nati_CallNativeFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_interact_nati_CallNativeFunction
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_interact_nati_CallNativeFunction_set
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_interact_nati_CallNativeFunction
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_interact_nati_CallNativeFunction_get
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
